// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import { NanoBufReader, NanoBufWriter, type NanoPackMessage } from "nanopack";

class ListViewOperation implements NanoPackMessage {
  public static TYPE_ID = 3516816492;

  public readonly typeId: number = 3516816492;

  public readonly headerSize: number = 8;

  constructor(public tag: number) {}

  public static fromBytes(
    bytes: Buffer,
  ): { bytesRead: number; result: ListViewOperation } | null {
    const reader = new NanoBufReader(bytes);
    return ListViewOperation.fromReader(reader);
  }

  public static fromReader(
    reader: NanoBufReader,
    offset = 0,
  ): { bytesRead: number; result: ListViewOperation } | null {
    let ptr = offset + 8;

    const tag = reader.readUint32(ptr);
    ptr += 4;

    return { bytesRead: ptr - offset, result: new ListViewOperation(tag) };
  }

  public writeTo(writer: NanoBufWriter, offset = 0): number {
    let bytesWritten = 8;

    writer.writeTypeId(3516816492, offset);

    writer.appendUint32(this.tag);
    writer.writeFieldSize(0, 4, offset);
    bytesWritten += 4;

    return bytesWritten;
  }

  public bytes(): Uint8Array {
    const writer = new NanoBufWriter(8);
    this.writeTo(writer);
    return writer.bytes;
  }
}

export { ListViewOperation };
