// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import { NanoBufReader } from "nanopack";

import { Widget } from "./widget.np.js";
import { Button } from "./button.np.js";
import { TextField } from "./text-field.np.js";
import { Row } from "./row.np.js";
import { Center } from "./center.np.js";
import { ListView } from "./list-view.np.js";
import { Column } from "./column.np.js";
import { Slider } from "./slider.np.js";
import { Text } from "./text.np.js";

function makeWidget(
  reader: NanoBufReader,
  offset = 0,
): { bytesRead: number; result: Widget } | null {
  switch (reader.readTypeId(offset)) {
    case 1676374721:
      return Widget.fromReader(reader, offset);
    case 320412644:
      return Button.fromReader(reader, offset);
    case 841129444:
      return TextField.fromReader(reader, offset);
    case 1006836449:
      return Row.fromReader(reader, offset);
    case 1855640887:
      return Center.fromReader(reader, offset);
    case 2164488861:
      return ListView.fromReader(reader, offset);
    case 2415007766:
      return Column.fromReader(reader, offset);
    case 3373588321:
      return Slider.fromReader(reader, offset);
    case 3495336243:
      return Text.fromReader(reader, offset);
    default:
      return null;
  }
}

export { makeWidget };
