// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import { NanoBufReader } from "nanopack";

import { ListViewOperation } from "./list-view-operation.np.js";
import { ListViewInsertOperation } from "./list-view-insert-operation.np.js";
import { ListViewDeleteOperation } from "./list-view-delete-operation.np.js";

function makeListViewOperation(
  reader: NanoBufReader,
  offset = 0,
): { bytesRead: number; result: ListViewOperation } | null {
  switch (reader.readTypeId(offset)) {
    case 3516816492:
      return ListViewOperation.fromReader(reader, offset);
    case 2077451345:
      return ListViewInsertOperation.fromReader(reader, offset);
    case 2223513129:
      return ListViewDeleteOperation.fromReader(reader, offset);
    default:
      return null;
  }
}

export { makeListViewOperation };
