// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import { NanoBufReader, NanoBufWriter, type NanoPackMessage } from "nanopack";

class SliderValueChangedEvent implements NanoPackMessage {
  public static TYPE_ID = 1030062961;

  public readonly typeId: number = 1030062961;

  public readonly headerSize: number = 8;

  constructor(public newValue: number) {}

  public static fromBytes(
    bytes: Buffer,
  ): { bytesRead: number; result: SliderValueChangedEvent } | null {
    const reader = new NanoBufReader(bytes);
    return SliderValueChangedEvent.fromReader(reader);
  }

  public static fromReader(
    reader: NanoBufReader,
    offset = 0,
  ): { bytesRead: number; result: SliderValueChangedEvent } | null {
    let ptr = offset + 8;

    const newValue = reader.readDouble(ptr);
    ptr += 8;

    return {
      bytesRead: ptr - offset,
      result: new SliderValueChangedEvent(newValue),
    };
  }

  public writeTo(writer: NanoBufWriter, offset = 0): number {
    let bytesWritten = 8;

    writer.writeTypeId(1030062961, offset);

    writer.appendDouble(this.newValue);
    writer.writeFieldSize(0, 8, offset);
    bytesWritten += 8;

    return bytesWritten;
  }

  public bytes(): Uint8Array {
    const writer = new NanoBufWriter(8);
    this.writeTo(writer);
    return writer.bytes;
  }
}

export { SliderValueChangedEvent };
