// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import { NanoBufReader, NanoBufWriter, type NanoPackMessage } from "nanopack";

class TextFieldChangedEvent implements NanoPackMessage {
  public static TYPE_ID = 2286117075;

  public readonly typeId: number = 2286117075;

  public readonly headerSize: number = 8;

  constructor(public newValue: string) {}

  public static fromBytes(
    bytes: Buffer,
  ): { bytesRead: number; result: TextFieldChangedEvent } | null {
    const reader = new NanoBufReader(bytes);
    return TextFieldChangedEvent.fromReader(reader);
  }

  public static fromReader(
    reader: NanoBufReader,
    offset = 0,
  ): { bytesRead: number; result: TextFieldChangedEvent } | null {
    let ptr = offset + 8;

    const newValueByteLength = reader.readFieldSize(0, offset);
    const newValue = reader.readString(ptr, newValueByteLength);
    ptr += newValueByteLength;

    return {
      bytesRead: ptr - offset,
      result: new TextFieldChangedEvent(newValue),
    };
  }

  public writeTo(writer: NanoBufWriter, offset = 0): number {
    let bytesWritten = 8;

    writer.writeTypeId(2286117075, offset);

    const newValueByteLength = writer.appendString(this.newValue);
    writer.writeFieldSize(0, newValueByteLength, offset);
    bytesWritten += newValueByteLength;

    return bytesWritten;
  }

  public bytes(): Uint8Array {
    const writer = new NanoBufWriter(8);
    this.writeTo(writer);
    return writer.bytes;
  }
}

export { TextFieldChangedEvent };
