// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import { NanoBufReader, NanoBufWriter, type NanoPackMessage } from "nanopack"

class CreateWindow implements NanoPackMessage {
	public static TYPE_ID = 10

	constructor(
		public title: string,
		public description: string,
		public width: number,
		public height: number,
		public tag: string,
	) {}

	public static fromBytes(
		bytes: Uint8Array,
	): { bytesRead: number; result: CreateWindow } | null {
		const reader = new NanoBufReader(bytes)

		let ptr = 24

		const titleByteLength = reader.readFieldSize(0)
		const title = reader.readString(ptr, titleByteLength)
		ptr += titleByteLength

		const descriptionByteLength = reader.readFieldSize(1)
		const description = reader.readString(ptr, descriptionByteLength)
		ptr += descriptionByteLength

		const width = reader.readInt32(ptr)
		ptr += 4

		const height = reader.readInt32(ptr)
		ptr += 4

		const tagByteLength = reader.readFieldSize(4)
		const tag = reader.readString(ptr, tagByteLength)
		ptr += tagByteLength

		return {
			bytesRead: ptr,
			result: new CreateWindow(title, description, width, height, tag),
		}
	}

	public get typeId(): number {
		return 10
	}

	public bytes(): Uint8Array {
		const writer = new NanoBufWriter(24)
		writer.writeTypeId(10)

		const titleByteLength = writer.appendString(this.title)
		writer.writeFieldSize(0, titleByteLength)

		const descriptionByteLength = writer.appendString(this.description)
		writer.writeFieldSize(1, descriptionByteLength)

		writer.appendInt32(this.width)
		writer.writeFieldSize(2, 4)

		writer.appendInt32(this.height)
		writer.writeFieldSize(3, 4)

		const tagByteLength = writer.appendString(this.tag)
		writer.writeFieldSize(4, tagByteLength)

		return writer.bytes
	}

	public bytesWithLengthPrefix(): Uint8Array {
		const writer = new NanoBufWriter(28, true)
		writer.writeTypeId(10)

		const titleByteLength = writer.appendString(this.title)
		writer.writeFieldSize(0, titleByteLength)

		const descriptionByteLength = writer.appendString(this.description)
		writer.writeFieldSize(1, descriptionByteLength)

		writer.appendInt32(this.width)
		writer.writeFieldSize(2, 4)

		writer.appendInt32(this.height)
		writer.writeFieldSize(3, 4)

		const tagByteLength = writer.appendString(this.tag)
		writer.writeFieldSize(4, tagByteLength)

		writer.writeLengthPrefix(writer.currentSize - 4)

		return writer.bytes
	}
}

export { CreateWindow }
