// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import { NanoBufReader, NanoBufWriter, type NanoPackMessage } from "nanopack"

class ReplyFromCallback implements NanoPackMessage {
	public static TYPE_ID = 370365707

	constructor(
		public to: number,
		public args: NanoBufReader,
	) {}

	public static fromBytes(
		bytes: Uint8Array,
	): { bytesRead: number; result: ReplyFromCallback } | null {
		const reader = new NanoBufReader(bytes)
		return ReplyFromCallback.fromReader(reader)
	}

	public static fromReader(
		reader: NanoBufReader,
	): { bytesRead: number; result: ReplyFromCallback } | null {
		let ptr = 12

		const to = reader.readInt32(ptr)
		ptr += 4

		const argsByteLength = reader.readFieldSize(1)
		const args = reader.newReaderAt(ptr, ptr + argsByteLength)
		ptr += argsByteLength

		return { bytesRead: ptr, result: new ReplyFromCallback(to, args) }
	}

	public get typeId(): number {
		return 370365707
	}

	public bytes(): Uint8Array {
		const writer = new NanoBufWriter(12)
		writer.writeTypeId(370365707)

		writer.appendInt32(this.to)
		writer.writeFieldSize(0, 4)

		writer.writeFieldSize(1, this.args.bytes.byteLength)
		writer.appendBytes(this.args.bytes)

		return writer.bytes
	}

	public bytesWithLengthPrefix(): Uint8Array {
		const writer = new NanoBufWriter(12 + 4, true)
		writer.writeTypeId(370365707)

		writer.appendInt32(this.to)
		writer.writeFieldSize(0, 4)

		writer.writeFieldSize(1, this.args.bytes.byteLength)
		writer.appendBytes(this.args.bytes)

		writer.writeLengthPrefix(writer.currentSize - 4)

		return writer.bytes
	}
}

export { ReplyFromCallback }
