// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import { NanoBufReader, NanoBufWriter, type NanoPackMessage } from "nanopack";

class ClickEvent implements NanoPackMessage {
  public static TYPE_ID = 837166865;

  public readonly typeId: number = 837166865;

  public readonly headerSize: number = 8;

  constructor(public timestamp: number) {}

  public static fromBytes(
    bytes: Buffer,
  ): { bytesRead: number; result: ClickEvent } | null {
    const reader = new NanoBufReader(bytes);
    return ClickEvent.fromReader(reader);
  }

  public static fromReader(
    reader: NanoBufReader,
    offset = 0,
  ): { bytesRead: number; result: ClickEvent } | null {
    let ptr = offset + 8;

    const timestamp = reader.readUint32(ptr);
    ptr += 4;

    return { bytesRead: ptr - offset, result: new ClickEvent(timestamp) };
  }

  public writeTo(writer: NanoBufWriter, offset = 0): number {
    let bytesWritten = 8;

    writer.writeTypeId(837166865, offset);

    writer.appendUint32(this.timestamp);
    writer.writeFieldSize(0, 4, offset);
    bytesWritten += 4;

    return bytesWritten;
  }

  public bytes(): Uint8Array {
    const writer = new NanoBufWriter(8);
    this.writeTo(writer);
    return writer.bytes;
  }
}

export { ClickEvent };
