// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import { NanoBufReader, NanoBufWriter, type NanoPackMessage } from "nanopack"

class InvokeCallback implements NanoPackMessage {
	public static TYPE_ID = 2

	constructor(public handle: number) {}

	public static fromBytes(
		bytes: Uint8Array,
	): { bytesRead: number; result: InvokeCallback } | null {
		const reader = new NanoBufReader(bytes)

		let ptr = 8

		const handle = reader.readInt32(ptr)
		ptr += 4

		return { bytesRead: ptr, result: new InvokeCallback(handle) }
	}

	public get typeId(): number {
		return 2
	}

	public bytes(): Uint8Array {
		const writer = new NanoBufWriter(8)
		writer.writeTypeId(InvokeCallback.TYPE_ID)

		writer.appendInt32(this.handle)
		writer.writeFieldSize(1, 4)

		return writer.bytes
	}
}

export { InvokeCallback }
