// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import { NanoBufReader, NanoBufWriter, type NanoPackMessage } from "nanopack"

class InvokeCallback implements NanoPackMessage {
	public static TYPE_ID = 2

	constructor(
		public handle: number,
		public args: NanoBufReader,
	) {}

	public static fromBytes(
		bytes: Uint8Array,
	): { bytesRead: number; result: InvokeCallback } | null {
		const reader = new NanoBufReader(bytes)
		return InvokeCallback.fromReader(reader)
	}

	public static fromReader(
		reader: NanoBufReader,
	): { bytesRead: number; result: InvokeCallback } | null {
		let ptr = 12

		const handle = reader.readInt32(ptr)
		ptr += 4

		const argsByteLength = reader.readFieldSize(1)
		const args = reader.newReaderAt(ptr, ptr + argsByteLength)
		ptr += argsByteLength

		return { bytesRead: ptr, result: new InvokeCallback(handle, args) }
	}

	public get typeId(): number {
		return 2
	}

	public bytes(): Uint8Array {
		const writer = new NanoBufWriter(12)
		writer.writeTypeId(2)

		writer.appendInt32(this.handle)
		writer.writeFieldSize(0, 4)

		writer.writeFieldSize(1, this.args.bytes.byteLength)
		writer.appendBytes(this.args.bytes)

		return writer.bytes
	}

	public bytesWithLengthPrefix(): Uint8Array {
		const writer = new NanoBufWriter(12 + 4, true)
		writer.writeTypeId(2)

		writer.appendInt32(this.handle)
		writer.writeFieldSize(0, 4)

		writer.writeFieldSize(1, this.args.bytes.byteLength)
		writer.appendBytes(this.args.bytes)

		writer.writeLengthPrefix(writer.currentSize - 4)

		return writer.bytes
	}
}

export { InvokeCallback }
